### ISSUE TITLE
Not listed in Package Control

### ISSUE THREAD

**Issue by karlingen** [david-soyez/sublime-yii-snippets#2]
This is no longer on the sublime repo. What happend?

**Comment by RubenDjOn** [comment]
Hi,
I'm using SublimeText 3, and Yii framework Snippets is not listed on the package list. See the image below.
![area de trabajo 2_469](https://cloud.githubusercontent.com/assets/805779/8130267/583dd450-1111-11e5-89ca-54a83bb13607.png)

Thanks.

**Comment by david-soyez** [comment]
Thank you, I juste noticed that the repository url was wrong in package
control. I just fixed it and no I wait form the merge to check again

2015-06-12 14:43 GMT+02:00 RubenDjOn <notifications@github.com>:
