### ISSUE TITLE
Snippets for Yii 2?

### ISSUE THREAD

**Issue by ThinkALot** [david-soyez/sublime-yii-snippets#4]
Are you planning to update these snippets for Yii 2? I think a Yii2 snippets plugin for Sublime Text would be a popular item.

Thanks.

**Comment by david-soyez** [comment]
No, unfortunately. I'm not using either Yii v1 or v2 or any other frameworks at the moment.

**Comment by ThinkALot** [comment]
Thanks for your reply. Do you have any advice for anyone who might want to update the snippets? 

Also, do you have any advice about frameworks in general, having stopped using them yourself? I'm new to frameworks, and recently picked Yii2 after carefully considering Laravel, Symphony, Cake, and CI. Any thoughts would be much appreciated.

Thanks.

**Comment by david-soyez** [comment]
As far as I know Symphony 2 is very popular in France (where I live)
Symfony 2 needs way more time to learn compared to Yii 1 or 2
If you want strict object, don't use Cake or CI because they are not.
I don't know anything about Lavarel.

**Comment by ThinkALot** [comment]
Thanks.
